Repository redBorder/cookbook-barnyard2, pull requests merged in 2024-04, with the labels that each got.

#4 change http mode for librb-http to deflated
  resources/templates/default/barnyard2.conf.erb
Labels: size/XS

#5 Release 0.0.6
  CHANGELOG.md
  resources/metadata.rb
Labels: size/XS, release, kind/documentation

#6 Added ../rpm.yml to .github/workflows/
  .github/workflows/rpm.yml
Labels: kind/documentation, size/M
